import { useParams, Link } from 'react-router-dom';
import { PublicLayout } from '@/components/layout/PublicLayout';
import { useArticle, useArticles } from '@/hooks/useArticles';
import { ArticleCard } from '@/components/news/ArticleCard';
import { SocialEmbed } from '@/components/news/SocialEmbed';
import { formatDate } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { ArrowLeft, Bot, Share2, Clock, Eye } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

const ArticleDetail = () => {
  const { id } = useParams<{ id: string }>();
  const { article, loading, error } = useArticle(id);
  const { toast } = useToast();

  // Fetch related articles from same category
  const { articles: relatedArticles } = useArticles({
    isPublished: true,
    category: article?.category,
    limit: 4,
  });

  // Filter out current article from related
  const filteredRelated = relatedArticles.filter(a => a.id !== id).slice(0, 3);

  const handleShare = async () => {
    if (navigator.share && article) {
      try {
        await navigator.share({
          title: article.title,
          url: window.location.href,
        });
      } catch {
        // User cancelled or error
      }
    } else {
      await navigator.clipboard.writeText(window.location.href);
      toast({
        title: "Link disalin!",
        description: "Link artikel telah disalin ke clipboard.",
      });
    }
  };

  if (loading) {
    return (
      <PublicLayout>
        <article className="container max-w-4xl py-8">
          <Skeleton className="h-8 w-24 mb-6" />
          <Skeleton className="h-12 w-full mb-4" />
          <Skeleton className="h-12 w-3/4 mb-6" />
          <div className="flex gap-4 mb-8">
            <Skeleton className="h-6 w-24" />
            <Skeleton className="h-6 w-32" />
          </div>
          <Skeleton className="w-full aspect-video rounded-lg mb-8" />
          <div className="space-y-4">
            {[1, 2, 3, 4, 5].map((i) => (
              <Skeleton key={i} className="h-6 w-full" />
            ))}
          </div>
        </article>
      </PublicLayout>
    );
  }

  if (error || !article) {
    return (
      <PublicLayout>
        <div className="container max-w-4xl py-16 text-center">
          <h1 className="font-headline text-2xl font-bold mb-4">Artikel Tidak Ditemukan</h1>
          <p className="font-body text-muted-foreground mb-6">
            Maaf, artikel yang Anda cari tidak tersedia.
          </p>
          <Link to="/">
            <Button>
              <ArrowLeft className="mr-2 h-4 w-4" />
              Kembali ke Beranda
            </Button>
          </Link>
        </div>
      </PublicLayout>
    );
  }

  return (
    <PublicLayout>
      <article className="container max-w-4xl py-8">
        {/* Back Button */}
        <Link to="/" className="inline-flex items-center text-muted-foreground hover:text-primary mb-6 font-sans text-sm transition-colors">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Kembali ke Beranda
        </Link>

        {/* Header */}
        <header className="mb-8">
          <div className="flex items-center gap-2 mb-4">
            <Badge variant="secondary">
              {article.category.charAt(0).toUpperCase() + article.category.slice(1)}
            </Badge>
            {article.source_url && (
              <Badge variant="outline" className="gap-1">
                <Bot className="h-3 w-3" />
                Generated by AI
              </Badge>
            )}
          </div>

          <h1 className="font-headline text-3xl md:text-4xl lg:text-5xl font-bold text-foreground leading-tight mb-6">
            {article.title}
          </h1>

          <div className="flex flex-wrap items-center gap-4 text-sm text-muted-foreground font-sans mb-6">
            <span className="flex items-center gap-1">
              <Clock className="h-4 w-4" />
              {formatDate(article.created_at)}
            </span>
            <span className="flex items-center gap-1">
              <Eye className="h-4 w-4" />
              {article.view_count} kali dibaca
            </span>
            <Button 
              variant="ghost" 
              size="sm" 
              onClick={handleShare}
              className="ml-auto"
            >
              <Share2 className="h-4 w-4 mr-2" />
              Bagikan
            </Button>
          </div>
        </header>

        {/* Featured Image */}
        {article.thumbnail_url && (
          <figure className="mb-8">
            <img
              src={article.thumbnail_url}
              alt={article.title}
              className="w-full aspect-video object-cover rounded-lg"
            />
          </figure>
        )}

        {/* Social Embed */}
        {article.source_url && (
          <SocialEmbed url={article.source_url} />
        )}

        {/* Content */}
        <div className="article-content text-news-body">
          {article.content.split('\n\n').map((paragraph, index) => (
            <p key={index}>{paragraph}</p>
          ))}
        </div>

        {/* Related Articles */}
        {filteredRelated.length > 0 && (
          <section className="mt-16 pt-8 border-t border-border">
            <h2 className="font-headline text-2xl font-bold mb-6">Baca Juga</h2>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
              {filteredRelated.map((relatedArticle) => (
                <ArticleCard key={relatedArticle.id} article={relatedArticle} />
              ))}
            </div>
          </section>
        )}
      </article>
    </PublicLayout>
  );
};

export default ArticleDetail;